=== Messionat45/wt-exp2/carSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cardata">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="car" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="companyname" type="xs:string"/>
                            <xs:element name="model" type="xs:string"/>
                            <xs:element name="engine" type="xs:string"/>
                            <xs:element name="mileage" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Messionat45/wt-exp2/car2.xml
<?xml version="1.0" encoding="utf-8"?>

<?xml-stylesheet type="text/xsl" href="car.xslt" ?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<cardata xsi:noNamespaceSchemaLocation="carSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <car id="100!!$#%^$^">
    <companyname>string</companyname>
    <model>string</model>
    <engine>string</engine>
    <mileage>string</mileage>
  </car>
  <car id="string">
    <companyname>string</companyname>
    <model>string</model>
    <engine>string</engine>
    <mileage>string</mileage>
  </car>
</cardata>

=== Messionat45/wt-exp2/car.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- including xslt file for stying -->
<?xml-stylesheet type="text/xsl" href="car.xslt" ?>

<!-- including DTD file for validation -->
<!DOCTYPE cardata SYSTEM "./ car.dtd" > 

<!-- including schema def file for validation .xsd -->
<cardata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./carSchema.xsd"> 

    <car id="100">
        <companyname>BMW</companyname>
        <model>X5</model>
        <engine>3.0L Turbo inline 6-cylinder</engine>
        <mileage>12kmpl</mileage>
    </car>
    <car id="101">
        <companyname>Tata</companyname>
        <model>Tiago</model>
        <engine>1.2 L, 3-cylinder</engine>
        <mileage>19.4kmpl</mileage>
    </car>
    <car id="102">
        <companyname>Renault</companyname>
        <model>Kwid</model>
        <engine>1.0 L 3-cylinder</engine>
        <mileage>22kmpl</mileage>
    </car>
    <car id="103">
        <companyname>Maruti Suzuki</companyname>
        <model>Brezza</model>
        <engine>1.5 L 4 cylinder </engine>
        <mileage>19.4kmpl</mileage>
    </car>
</cardata>
